### ISSUE TITLE
Speed up searchcaster full text search

### ISSUE THREAD

**Issue by TimDaub** [gskril/farcaster-indexer#19]
- Yesterday, I asked on Farcaster whether it is possible to speed up query search results for searchcaster
- I looked into the code and found that it is using the LIKE syntax for text search: https://github.com/gskril/searchcaster/blob/main/src/pages/api/search.js#L162
- I looked through the database migrations to find if a specific full text search index was created: https://github.com/gskril/farcaster-indexer/tree/main/supabase/migrations (it doesn't look like it)

My plan is now to:

- successfully seed the indexer
- run a test query using full text search (and record the time it took)
- work through https://www.postgresql.org/docs/current/datatype-textsearch.html and see if I can improve search result performance
- if so, send a PR

**Comment by TimDaub** [comment]
Here's a query that takes a very long time and this is due to me adding the ORDER subquery

```
select * from casts WHERE text ILIKE '%of%' AND deleted=false order by reactions_count;
```

**Comment by TimDaub** [comment]
- To optimize this call: https://github.com/gskril/searchcaster/blob/d1baa79242e7a3e1db3183a3c8b27c9b30bcf832/src/pages/api/search.js#L158-L179

which I'm simulating as follows

```
SELECT *
FROM casts
WHERE to_tsvector('english', text) @@ to_tsquery('english', 'searchcaster') AND deleted=false
ORDER BY reactions_count;
```

where the "reactions_count" slows down the query significantly. Without indexes:

```
postgres=# SELECT * FROM casts WHERE to_tsvector('english', text) @@ to_tsquery('english', 'searchcaster') AND deleted=false ORDER BY reactions_count;
Time: 2110.693 ms (00:02.111)
```

So I'm creating an index over all fields that could be queried as follows

```sql
CREATE INDEX casts_text_gin_index ON casts USING gin(to_tsvector('english', text));
CREATE INDEX casts_published_at_index ON casts USING btree(published_at, deleted, recasts_count, replies_count, watches_count, author_username);
```

New performance with indexes

```
postgres=# \timing
Timing is on.
postgres=# SELECT * FROM casts WHERE to_tsvector('english', text) @@ to_tsquery('english', 'searchcaster') AND deleted=false ORDER BY reactions_count;
Time: 29.832 ms
```

**Comment by psatyajeet** [comment]
Love this!

`ilike` is case-insensitive. is the query that uses `to_tsvector @@ to_tsquery` also case-insensitive?

**Comment by TimDaub** [comment]
Haven‘t found anything definitive in the docs, we can do tests though. But I think it goes even beyond understanding capitalization as it also understands verb conjugations etc

> Converting tokens into lexemes. A lexeme is a string, just like a token, but it has been normalized so that different forms of the same word are made alike. For example, normalization almost always includes folding upper-case letters to lower-case, and often involves removal of suffixes (such as s or es in English).

https://www.postgresql.org/docs/9.4/textsearch-intro.html
