### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by spaceh3ad** [gskril/farcaster-indexer#27]
Hello, please add information what hardware specs are needed to run indexer.

**Comment by gskril** [comment]
The minimum hardware required to run a hub is
- 16 GB of RAM
- 4 CPU cores or vCPUs
- 40 GB of free storage

The indexer + Postgres will consume additional resources but I don't have exact numbers. I'm currently running everything on a c2.small.x86 [Latitude](https://www.latitude.sh/r/673C7DB2) bare metal server (referral link for free credits).
