### ISSUE TITLE
Insert links error: bind message has 38010 parameter formats but 0 parameters.

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [gskril/farcaster-indexer#34]
<img width="1090" alt="image" src="https://github.com/gskril/farcaster-indexer/assets/12232001/d0a93bdf-dbb4-4f80-b308-68b6030ace63">
I don't know the reason and how to fix it?

**Comment by gskril** [comment]
This should have been fixed as of [this commit](https://github.com/gskril/farcaster-indexer/commit/8e612aa07c1e662db762c783a8416f4955537a4e) 5 days ago. Are you on the latest version?

**Comment by jiayuxiaochaoren** [comment]
> This should have been fixed as of [this commit](https://github.com/gskril/farcaster-indexer/commit/8e612aa07c1e662db762c783a8416f4955537a4e) 5 days ago. Are you on the latest version?

Sorry,I'm not on the latest version. 
I will update the latest version. Thank you for your reply.
