### ISSUE TITLE
Return all grandchildren and ancestors per cast fetch

### ISSUE THREAD

**Issue by vinliao** [gskril/farcaster-indexer#6]
Currently, if devs fetch a cast from Searchcaster, it returns children with depth 1. Would it be desirable if it returns all the grandkids per fetch? HN and Reddit does this - when users view a post, all the comments of that post gets displayed. The API looks like this: https://hn.algolia.com/api/v1/items/33757484 (notice that the "children" key recursively contains all the replies). Plus, it would be extra nice if it also returns all the ancestors (all the casts from the root thread to the fetched cast, if there's any).

I'm down to help to make this happen.

**Comment by gskril** [comment]
Hey @vinliao, sorry for the late reply! I definitely agree that it would be desirable to return all related casts (children and ancestors). This will be made much easier once I get a chance to migrate to the Farcaster V2 client APIs thanks to the `threadMerkleRoot` property. I just haven't looked much into those yet.

In the meantime, it's worth noting that there is a (maybe soon-to-be deprecated but still used in the main client) endpoint that does what you're talking about and may be worth exploring: https://api.farcaster.xyz/indexer/threads/0x51bc4b1bc6136ef4fc359f05d74c240e420cd8e46a98faae407b4b0a62e62160?viewer_address=0x0000000000000000000000000000000000000000

**Comment by vinliao** [comment]
What sort of help do you need in migrating into the V2 APIs? If you lay them all out, perhaps us FC devs can help out with PRs.

(Thank you for the link. I was trying to look exactly for that, but couldn't find it anywhere!)

**Comment by gskril** [comment]
Circling back here — sorry for the delay but I just migrated everything to V2 APIs with https://github.com/gskril/farcaster-indexer/pull/7

We now store `threadMerkleRoot` for all casts. The Searchcaster endpoint currently still returns direct children only, but it would be much easier now to implement your suggestion of grandchildren and ancestors. Totally open to a PR on Searchcaster :)

**Comment by vinliao** [comment]
I see. I have implemented a `getAncestor()` function: (https://github.com/vinliao/phrasetown/blob/e466c5009f42176e37577a06769858d43118d342/src/routes/cast/%5Bhash%5D/%2Bpage.server.ts#L43). Takes in all replies, thread hash, cast hash, then returns an array of ancestors. Kinda short, perhaps could be implemented on Searchcaster?

**Comment by vinliao** [comment]
Hi, Greg. I just want to close the loop on this. I've implemented multiple algorithms discussed here (and more) on the Phrasetown API. Will make documentation soon. Thank you very much!
